name: whossy_app
description: "The mobile app for Whossy"
publish_to: 'none' # Prevents accidental publication to pub.dev
version: 1.0.0+1801

environment:
  sdk: '>=3.3.4 <4.0.0'

# Core Flutter Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6 # iOS-style icons

  # Firebase - Core Features
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  firebase_database: ^11.1.4
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  firebase_app_check: ^0.3.0+4
  firebase_messaging: ^15.1.3

  # Authentication & Connectivity
  google_sign_in: ^6.2.1
  connectivity_plus: ^6.0.4
  internet_connection_checker: ^1.0.0+1

  # UI & Animation Libraries
  flutter_screenutil: ^5.9.3 # Responsive design
  lottie: ^3.1.2 # Animations
  flutter_svg: ^2.0.10+1 # SVG handling
  shimmer: ^3.0.0 # Loading effects
  modal_bottom_sheet: ^3.0.0 # Custom bottom sheet dialogs

  # UI Elements - Custom & Core
  iconly: ^1.0.1 # Icons
  top_snackbar_flutter: ^3.1.0 # Snack bars
  pin_code_fields: ^8.0.1 # PIN fields
  readmore: ^3.0.0 # Expandable text
  flutter_staggered_grid_view: ^0.7.0 # Staggered grid layout
  cupertino_range_slider_improved: ^2.0.1

  # Image & Media Processing
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  cached_network_image: ^3.4.1

  # Additional Functionalities
  provider: ^6.1.2 # State management
  url_launcher: ^6.3.0 # Opening URLs
  email_validator: ^3.0.0 # Email validation
  flutter_vibrate: ^1.3.0 # Vibration
  intl: ^0.19.0 # Internationalization
  uuid: ^4.5.1 # Unique IDs
  permission_handler: ^11.3.1 # Permissions
  path: ^1.9.0 # Path management
  flutter_local_notifications: ^17.2.3
  shared_preferences: ^2.3.2
  json_annotation: ^4.9.0
  flutter_hooks: ^0.20.5
  collection: ^1.18.0
  geolocator: ^13.0.1
  # geoflutterfire: ^3.0.3

  # Navigation
  auto_route: ^9.2.2 # Routing

  # Swipe Interaction
  flutter_card_swiper: ^7.0.2 # Card swipe functionality

  # Git Dependencies
  country_picker:
    git:
      url: https://github.com/devBamidele/flutter_country_picker.git
      ref: dev

# Development Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Linting
  auto_route_generator: ^9.0.0 # Code generation for routes
  build_runner: # Code generation
  json_serializable: ^6.8.0 # JSON serialization

# Flutter-Specific Settings
flutter:
  uses-material-design: true

  # Asset Configuration
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/Neue_Montreal/
    - assets/animations/

  # Font Configuration
  fonts:
    - family: NeueMontreal
      fonts:
        - asset: assets/fonts/Neue_Montreal/NeueMontreal-Bold.otf
          weight: 700
          style: normal
        - asset: assets/fonts/Neue_Montreal/NeueMontreal-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Neue_Montreal/NeueMontreal-Italic.otf
          style: italic
        - asset: assets/fonts/Neue_Montreal/NeueMontreal-Light.otf
          weight: 300
          style: normal
        - asset: assets/fonts/Neue_Montreal/NeueMontreal-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Neue_Montreal/NeueMontreal-Medium.otf
          weight: 500
          style: normal
        - asset: assets/fonts/Neue_Montreal/NeueMontreal-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Neue_Montreal/NeueMontreal-Regular.otf
          weight: 400
          style: normal
