// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3qDpFpJYWJ_KmSw-6E9tnIfV0VLvw_gQ',
    appId: '1:332139466657:android:51356c8ce9a7890c2d05e0',
    messagingSenderId: '332139466657',
    projectId: 'whossy-app',
    storageBucket: 'whossy-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_oRz_e1SuilF_2jxwmQj7ktZE4qdcvaI',
    appId: '1:332139466657:ios:c27fc2e2540b7cbc2d05e0',
    messagingSenderId: '332139466657',
    projectId: 'whossy-app',
    storageBucket: 'whossy-app.appspot.com',
    androidClientId: '332139466657-t725bl7kn9c688oeprb0gvmv291lhafb.apps.googleusercontent.com',
    iosClientId: '332139466657-us1ftnf9udotuhh0oltffvd48isqe0ju.apps.googleusercontent.com',
    iosBundleId: 'com.whossy.whossyApp',
  );

}