final alphabet = [
  {
    'letter': 'A',
    'options': [
      'Art',
      'Art galleries',
      'Atari',
      'Archery',
      'Acapella',
      'Among us',
      'Acai',
      'Anime',
      'Artistic swimming',
      'Athletics',
      'Activism',
      'Aquarium',
      'Achievements',
      'Apex',
    ],
  },
  {
    'letter': 'B',
    'options': [
      'Bollywood',
      'Basketball',
      'Black lives matter',
      'Beach bars',
      'Body pump',
      'Bowling',
      'Body step',
      'Body combat',
      'Binge-watching TV shows',
      'Bicycle racing',
      'Black pink',
      'Body jam',
      'Broadway',
      'BBQ',
      'Board games',
      'Books',
      'Baseball',
      'Bassist',
      'Boxing',
      'Bar chilling',
      'Beach tennis',
    ],
  },
  {
    'letter': 'C',
    'options': [
      'Cooking',
      'Camping',
      'Chess',
      'Cycling',
      'Concerts',
      'Cosplay',
      'Crafts',
      'Climbing',
      'Comedy',
      'Cinema',
      'Coding',
      'Calligraphy',
      'Cats',
      'Coffee',
      'Crochet',
      'Card games',
      'Cocktails',
      'Capoeira',
      'Car racing',
      'Charity work',
      'Cartooning',
      'Cheerleading',
    ],
  },
  {
    'letter': 'D',
    'options': [
      'Dancing',
      'Dogs',
      'Drawing',
      'Diving',
      'DIY',
      'Drama',
      'Debates',
      'Darts',
      'DJing',
      'Disney',
      'Dodgeball',
      'Dinosaurs',
      'Desserts',
      'Documentaries',
      'Digital art',
      'Dungeons & Dragons',
    ],
  },
  {
    'letter': 'E',
    'options': [
      'Electronics',
      'Equestrian sports',
      'Escape rooms',
      'Esports',
      'Experimental music',
      'Exhibitions',
      'Eating out',
      'Egg painting',
      'Environmental conservation',
      'Engineering',
      'Entrepreneurship',
      'Exercise',
      'Egyptology',
      'Ethnography',
      'Entomology',
      'Engraving',
      'Eating competitions',
      'Ethical fashion',
      'Economics',
      'Education',
      'Event planning',
    ],
  },
  {
    'letter': 'F',
    'options': [
      'Fashion',
      'Fishing',
      'Football',
      'Festivals',
      'Fitness',
      'Fine arts',
      'Fencing',
      'Film making',
      'Food',
      'Freestyle dancing',
      'Fireworks',
      'Fairy tales',
      'Furniture restoration',
      'Fashion design',
      'Fossil hunting',
      'Falconry',
      'Folklore',
      'Flower arranging',
      'Flag football',
      'Forensic science',
      'Fitness training',
    ],
  },
  {
    'letter': 'G',
    'options': [
      'Gardening',
      'Gaming',
      'Golf',
      'Graffiti art',
      'Gymnastics',
      'Geocaching',
      'Glass art',
      'Graphic design',
      'Gastronomy',
      'Gliding',
      'Gaming tournaments',
      'Gangster movies',
      'Gin tasting',
      'Greek mythology',
      'Genealogy',
      'Gospel music',
      'Glassblowing',
      'Gym',
      'Gunsmithing',
      'Guitar',
    ],
  },
  {
    'letter': 'H',
    'options': [
      'Hiking',
      'Horseback riding',
      'History',
      'Hockey',
      'Hula hooping',
      'Hunting',
      'Hip hop music',
      'Holography',
      'Handicrafts',
      'Health and fitness',
      'Horror movies',
      'Horse racing',
      'Hang gliding',
      'Hats',
      'Herbalism',
      'Heavy metal music',
      'Home brewing',
      'Hammock camping',
      'Humor',
      'Harmonica',
      'Historical reenactments',
    ],
  },
  {
    'letter': 'I',
    'options': [
      'Ice skating',
      'Illustration',
      'Inline skating',
      'Ice climbing',
      'Inventing',
      'Indie music',
      'Interior design',
      'Ice hockey',
      'Instrument making',
      'Improvisation',
      'Information technology',
      'Investing',
      'Ironman triathlon',
      'Instagramming',
      'Indigenous cultures',
      'Ice fishing',
      'Ice cream tasting',
      'Insect collecting',
      'Italian food',
      'Influencer',
      'Ice carving',
    ],
  },
  {
    'letter': 'j',
    'options': [
      'Jazz music',
      'Jewelry making',
      'Jogging',
      'Judo',
      'Juggling',
      'Jet skiing',
      'Journaling',
      'Japanese culture',
      'Jazzercise',
      'Juicing',
      'Jump rope',
      'Jamming',
      'Jigsaw puzzles',
      'Jeep riding',
      'Jazz dancing',
      'Jamaican cuisine',
      'Jousting',
      'Japanese anime',
      'Java programming',
      'Jewelry design',
    ],
  },
  {
    'letter': 'k',
    'options': [
      'Karaoke',
      'Kitesurfing',
      'Kayaking',
      'Kickboxing',
      'Knitting',
      'K-pop music',
      'Karate',
      'Kite flying',
      'Kart racing',
      'Kitchen gardening',
      'Kneeboarding',
      'Knife throwing',
      'Kombucha brewing',
      'Korean dramas',
      'Kites',
      'Kegging beer',
      'Kabuki theater',
      'Kakuro puzzles',
      'Kaleidoscope making',
      'Keno',
      'Knifemaking',
    ],
  },
  {
    'letter': 'l',
    'options': [
      'Listening to music',
      'Lacrosse',
      'Lego building',
      'Laser tag',
      'Languages',
      'LARPing',
      'Laser engraving',
      'Luge',
      'Lindy hop',
      'Live music',
      'Lawn bowling',
      'Leatherworking',
      'Lip sync battles',
      'Literature',
      'Lockpicking',
      'Lawn mowing',
      'Longboarding',
      'Lithography',
      'Line dancing',
      'Luxury cars',
      'Lacquer art',
    ],
  },
  {
    'letter': 'm',
    'options': [
      'Music',
      'Movies',
      'Martial arts',
      'Mountaineering',
      'Museum visits',
      'Magic tricks',
      'Metal detecting',
      'Meditation',
      'Manga',
      'Mountain biking',
      'Mask making',
      'Mosaics',
      'Model building',
      'Mushroom hunting',
      'Mindfulness',
      'Macrame',
      'Molecular gastronomy',
      'Makeup tutorials',
      'Microbrewing',
      'Miniature golf',
    ],
  },
  {
    'letter': 'n',
    'options': [
      'Nature walks',
      'Nordic skiing',
      'Nail art',
      'Nunchaku',
      'Nutrition',
      'Networking',
      'Nordic walking',
      'Novels',
      'Ninjutsu',
      'Numismatics',
      'Nanotechnology',
      'Nudism',
      'Night sky watching',
      'Neon art',
      'Netball',
      'Napping',
      'Naval history',
      'Nerf war',
      'Nautical science',
      'Nihonto',
      'Nylon crafts',
    ],
  },
  {
    'letter': 'o',
    'options': [
      'Origami',
      'Outdoor activities',
      'Orienteering',
      'Opera',
      'Off-roading',
      'Organic gardening',
      'Online gaming',
      'Oxygen therapy',
      'Oud music',
      'Olympic weightlifting',
      'Ornithology',
      'Obstacle courses',
      'Oil painting',
      'Open source projects',
      'Orchestra',
      'Oceans',
      'Oyster shucking',
      'Oboe',
      'Oceanography',
      'Optometry',
      'Ostrich racing',
    ],
  },
  {
    'letter': 'p',
    'options': [
      'Painting',
      'Photography',
      'Piano',
      'Paragliding',
      'Pottery',
      'Parkour',
      'Podcasts',
      'Poetry',
      'Paddleboarding',
      'Philosophy',
      'Pilates',
      'Puppetry',
      'Pasta making',
      'Paranormal investigation',
      'Poker',
      'Pet care',
      'Paddle tennis',
      'Pancake art',
      'Pickleball',
      'Piloting',
      'Paper crafts',
    ],
  },
  {
    'letter': 'q',
    'options': [
      'Quilting',
      'Quizzes',
      'Quad biking',
      'Quidditch',
      'Quilling',
      'Quality time',
      'Quick draw',
      'Qigong',
      'Quadcopter racing',
      'Quilombo',
      'Quantum mechanics',
      'Quests',
      'Quakerism',
      'Qawwali music',
      'Quantum computing',
      'Quartz cutting',
      'Queer culture',
      'Questioning everything',
      'Queen collecting',
      'Quarantine crafts',
      'Quartz',
    ],
  },
  {
    'letter': 'r',
    'options': [
      'Reading',
      'Running',
      'Rowing',
      'Rock climbing',
      'Rugby',
      'Rap music',
      'Racquetball',
      'Robotics',
      'Renaissance art',
      'Radio-controlled cars',
      'Rhythmic gymnastics',
      'Role-playing games',
      'Rope skipping',
      'Rodeo',
      'Renovating',
      "Rubik's cubes",
      'Railroad history',
      'Rain dancing',
      'Racing',
      'Rustic cooking',
      'Retro gaming',
    ],
  },
  {
    'letter': 's',
    'options': [
      'Swimming',
      'Soccer',
      'Sailing',
      'Scuba diving',
      'Sculpture',
      'Surfing',
      'Skydiving',
      'Skateboarding',
      'Skiing',
      'Snorkeling',
      'Snowboarding',
      'Street art',
      'Stand-up comedy',
      'Spelunking',
      'Samba',
      'Salsa dancing',
      'Squash',
      'Sumo wrestling',
      'Snooker',
      'Spinning',
      'Sewing',
    ],
  },
  {
    'letter': 't',
    'options': [
      'Traveling',
      'Tennis',
      'Table tennis',
      'Trekking',
      'Tae kwon do',
      'Tap dancing',
      'Trampoline',
      'Triathlons',
      'Trail running',
      'Tarot card reading',
      'Tattooing',
      'Toy collecting',
      'Trombone',
      'Thrift shopping',
      'Twerking',
      'Time travel',
      'Taxidermy',
      'Theater',
      'Tea tasting',
      'Trivia',
    ],
  },
  {
    'letter': 'u',
    'options': [
      'Ultimate Frisbee',
      'Unicycling',
      'Urban exploration',
      'Underwater hockey',
      'Ultimate fighting',
      'Upcycling',
      'Ukulele',
      'Underwater diving',
      'Urban gardening',
      'Urban art',
      'Ufology',
      'Ultimate tournaments',
      'Ultramarathons',
      'Unconventional sports',
      'Upside-down cooking',
      'Umbrella painting',
      'Urban farming',
      'Urban planning',
      'Umbrella crafting',
      'Upholstery',
    ],
  },
  {
    'letter': 'v',
    'options': [
      'Video games',
      'Vlogging',
      'Violin',
      'Vegetarian cooking',
      'Virtual reality',
      'Vibraphone',
      'Vinyl records',
      'Volleyball',
      'Voice acting',
      'Veganism',
      'Vineyard tours',
      'Venture capitalism',
      'Virtual pet breeding',
      'Vinyl cutting',
      'Ventriloquism',
      'Viking history',
      'Victorian fashion',
      'Vehicle restoration',
      "Valentine's crafts",
      'Vikings',
    ],
  },
  {
    'letter': 'w',
    'options': [
      'Writing',
      'Wrestling',
      'Water skiing',
      'Windsurfing',
      'Woodworking',
      'Whale watching',
      'Wine tasting',
      'Waltz',
      'Wildlife photography',
      'Wingsuit flying',
      'Wine making',
      'Wind chime making',
      'Weaving',
      'Wine collecting',
      'Wushu',
      'Whittling',
      'Witchcraft',
      'Web development',
      'Wood carving',
      'Water polo',
      'Whiskey tasting',
    ],
  },
  {
    'letter': 'x',
    'options': [
      'Xylophone playing',
      'X-ray photography',
      'X-treme sports',
      'Xenology',
      'Xerography',
      'Xenotransplantation',
      'Xylitol production',
      'Xiangqi',
      'Xenodochy',
      'Xanadu appreciation',
      'Xanthan gum making',
      'Xiphoidectomy',
      'Xebec racing',
      'Xenobiotics study',
      'Xylography',
      'Xyster sharpening',
      'Xenogenesis',
      'Xenophobia',
      'Xerothermism',
      'Xiphos design',
      'Xiphias hunting',
    ],
  },
  {
    'letter': 'y',
    'options': [
      'Yoga',
      'Yo-yoing',
      'Yachting',
      'Yarn spinning',
      'Youth mentoring',
      'Yoiking',
      'Yard games',
      'Yodeling',
      'Yarning',
      'Yarn bombing',
      'Yantra painting',
      'Yummy cooking',
      'Yukigassen',
      'Yard work',
      'Yoyos',
    ],
  },
  {
    'letter': 'z',
    'options': [
      'Zumba',
      'Ziplining',
      'Zither playing',
      'Zorbing',
      'Zen meditation',
      'Zeppelin flying',
      'Zookeeping',
      'Zazen',
      'Zombie hunting',
      'Zamboni driving',
      'Zoo visits',
      'Zither making',
      'Zoetrope animation',
      'Zither crafting',
      'Zumba classes',
      'Zebrafish breeding',
      'Zipline photography',
      'Zebu raising',
      'Zinc mining',
      'Zebu wrestling',
      'Zumba fitness',
    ],
  },
];
